# Generated by Django 4.0.2 on 2022-03-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_devices'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='status',
            field=models.CharField(choices=[('online', 'online'), ('offline', 'offline')], default='offline', max_length=100),
        ),
    ]
